[package]
name = "ragent_derive"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
# DeriveInput uses Syn's default derive/parsing support; full Rust syntax is unnecessary.
syn = "2.0.39"
quote = "1.0.33"
proc-macro-crate = "3.2.0"
proc-macro2 = "1.0.92"
